nword: nword_calc.c
	gcc nword_calc.c -o nword
test: nword
	./nword "I know that Rabbit runs fast but the hourse sd fg shsdh sd is ds dfg sg dfsg tsh sdh shr sdtha r ah better, I think,      for any man that wants to go to some place. I love to eat rabbit and ride a hourse wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait wait"
